/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login using a username and a password. */
    post: operations['login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/signup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sign up for a new account. */
    post: operations['signup'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Logout of current session.
     * @description No request body required.
     */
    post: operations['logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/products': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Gets all products.
     * @description Gets a list of 25 products per page and allows pagination through query parameters.
     */
    get: operations['get_products'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/products/{productId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The id of the product. */
        productId: components['parameters']['productIdParam'];
      };
      cookie?: never;
    };
    /**
     * Get single product by id.
     * @description Includes all of the product's data, including average rating, total ratings, total orders, and more.
     */
    get: operations['get_product_by_id'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/products/{productId}/reviews': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all reviews for a specific product. */
    get: operations['get_reviews_by_product'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/customers/{customerId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description The id of the customer.
         * @default 1
         */
        customerId: components['parameters']['customerIdParam'];
      };
      cookie?: never;
    };
    /**
     * Get all of a customer's data.
     * @description Get all of a customer's data, including billing and shipping address.
     */
    get: operations['get_customer_by_id'];
    /**
     * Update customer details.
     * @description Allows customer to update own account details.
     */
    put: operations['update_customer'];
    post?: never;
    /**
     * Delete a customer
     * @description Deletes all data for a specific customer - their account, all of their orders and wishlist.
     */
    delete: operations['delete_customer'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/customers/{customerId}/cart': {
    parameters: {
      query?: {
        /** @description allows user to choose between different JSON formats for the response object */
        format?: components['parameters']['formatParam'];
      };
      header?: never;
      path: {
        /**
         * @description The id of the customer.
         * @default 1
         */
        customerId: components['parameters']['customerIdParam'];
      };
      cookie?: never;
    };
    /**
     * Get customer's cart items.
     * @description View all of a customer's cart items, in a full format or as a simplified array.
     */
    get: operations['get_cart_items'];
    /**
     * Update cart.
     * @description Allows customer to remove or add cart items and to modify their quantities.
     */
    put: operations['udpate_cart'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/customers/{customerId}/wishlist': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The id of the customer. */
        customerId: string;
      };
      cookie?: never;
    };
    /**
     * Get customer's wishlist items.
     * @description Get all items that the customer has added to their wishlist.
     */
    get: operations['get_wishlist_items'];
    /**
     * Update wishlist.
     * @description Allows customer to add or remove items from their wishlist.
     */
    put: operations['update_wishlist'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/customers/{customerId}/orders': {
    parameters: {
      query?: {
        /** @description returns date and id of the most recent order containing this item, or null if the customer has not previously ordered this item. */
        productId?: components['parameters']['productIdQueryParam'];
      };
      header?: never;
      path: {
        /**
         * @description The id of the customer.
         * @default 1
         */
        customerId: components['parameters']['customerIdParam'];
      };
      cookie?: never;
    };
    /**
     * Get customer's orders.
     * @description Get all orders for a specific customer, including dates, addresses and products ordered.
     */
    get: operations['get_orders'];
    put?: never;
    /**
     * Create new order.
     * @description Creates a new order for that customer, either using all of their cart items or a single item provided in the request body.
     */
    post: operations['create_order'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/customers/{customerId}/favorites': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The id of the customer. */
        customerId: string;
      };
      cookie?: never;
    };
    /**
     * Get customer's recommended items.
     * @description Get all items that have been recommended in reviews by a customer.
     */
    get: operations['get_favorites'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/customers/{customerId}/orders/{orderId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description The id of the customer.
         * @default 1
         */
        customerId: components['parameters']['customerIdParam'];
        /** @description The id of the order. */
        orderId: components['parameters']['orderIdParam'];
      };
      cookie?: never;
    };
    /**
     * Get single order.
     * @description Get all data about a specific order.
     */
    get: operations['get_order_by_id'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/customers/{customerId}/reviews': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description The id of the customer.
         * @default 1
         */
        customerId: components['parameters']['customerIdParam'];
      };
      cookie?: never;
    };
    /**
     * Get all reviews posted by a customer.
     * @description Get a paginated list of reviews.
     */
    get: operations['get_reviews_by_customer'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/customers/{customerId}/addresses': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description The id of the customer.
         * @default 1
         */
        customerId: components['parameters']['customerIdParam'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create or modify address.
     * @description Allows customer to create or modify billing or shipping address.
     */
    post: operations['create_address'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/customers/{customerId}/addresses/{addressId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description The id of the customer.
         * @default 1
         */
        customerId: components['parameters']['customerIdParam'];
        /** @description The id of the address. */
        addressId: components['parameters']['addressIdParam'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete address.
     * @description Allows customer to delete their billing or shipping address.
     */
    delete: operations['delete_address'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/categories': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all categories. */
    get: operations['get_categories'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/suppliers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all suppliers. */
    get: operations['get_suppliers'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/reviews': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all reviews. */
    get: operations['get_reviews'];
    put?: never;
    /**
     * Post a new review.
     * @description Allows customer to post a new review for an item they have previously purchased and not yet reviews.
     */
    post: operations['update_review'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/reviews/{reviewId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The id of the review. */
        reviewId: components['parameters']['reviewIdParam'];
      };
      cookie?: never;
    };
    /**
     * Get single review.
     * @description Returns a single review object, matching the provided id.
     */
    get: operations['get_review_by_id'];
    /**
     * Modify an existing review.
     * @description Allows customer to modify a variable/unknown number of attributes for a  single review.
     */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description The id of the review. */
          reviewId: components['parameters']['reviewIdParam'];
        };
        cookie?: never;
      };
      /** @description optional fields can be specified to modify the review's attributes */
      requestBody?: {
        content: {
          'application/json': {
            customerId?: number;
            productId?: number;
            title?: string;
            body?: string;
            recommend?: boolean | null;
            rating?: number;
          };
        };
      };
      responses: {
        /** @description Returns the updated review */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              updatedReview?: components['schemas']['Review'];
            };
          };
        };
        400: components['responses']['BadRequest'];
        404: components['responses']['NotFound'];
      };
    };
    post?: never;
    /**
     * Delete a review.
     * @description Delete a specific review from the customer's reviews.
     */
    delete: operations['delete_review'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Address: {
      /** @example 123 Fake Street */
      addressLine1?: string;
      /** @example Flat 12 */
      addressLine2?: string | null;
      /** @example Kanzua */
      city?: string;
      /** @example Narnborough */
      county?: string | null;
      /** @example NN12 4FS */
      postcode?: string;
    };
    Login: {
      username?: string;
      password?: string;
    };
    Signup: {
      /** @example <ENTER_UNIQUE_USERNAME> */
      username?: string;
      /** @example password123abc */
      password?: string;
      /** @example Marcus Boone */
      name?: string;
      /** @example boone@raza.net */
      email?: string;
      /** @example +44 0776527762 */
      phone?: string;
      /** @example null */
      avatar?: string;
    };
    SingleOrderBase: {
      /** @example 322 */
      id?: number;
      /** @example 2 */
      customerId?: number;
      /** @example 12 */
      billingAddressId?: number;
      /** @example 12 */
      shippingAddressId?: number;
      /** @example completed */
      status?: string;
      /** @enum {string} */
      paymentMethod?: 'Card' | 'PayPal' | 'Klarna';
      /** @example 2024-02-07T04:19:59.667Z */
      createdAt?: string;
      shippingAddress?: components['schemas']['Address'];
      orderItems?: {
        /** @example 3 */
        quantity?: number;
        product?: components['schemas']['ProductShort'];
      }[];
    };
    SingleOrder: components['schemas']['SingleOrderBase'] & {
      billingAddress?: components['schemas']['Address'];
    };
    Orders: {
      /** @example 1 */
      id?: number;
      /** @example Alex Nes */
      name?: string;
      /** @example alexnes */
      username?: string;
      orders?: components['schemas']['SingleOrderBase'][];
    };
    ProductShort: {
      /** @example 1 */
      id?: number;
      /** @example Rechargebale batteries */
      name?: string;
      /** @example Product description */
      description?: string;
      /** @example 20.33 */
      price?: string;
      /** @example 55 */
      stock?: number;
      /** @example Electronics */
      categoryName?: string;
      /** @example Lectronics LTD */
      supplierName?: string;
      /** @example www.thumbnails.com/1 */
      thumbnail?: string;
    };
    Product: components['schemas']['ProductShort'] & {
      /** @example 10 */
      numOfTimesOrdered?: number;
      /** @example 23 */
      totalUnitsOrdered?: number;
      /** @example 5 */
      numOfReviews?: number;
      /** @example 2.3 */
      averageRating?: string;
    };
    Customer: {
      /** @example 1 */
      id?: number;
      /** @example Alex Nes */
      name?: string;
      /** @example alexnes33 */
      username?: string;
      /** @enum {string} */
      password?: '**********';
      /** @example cdweller@vg.co.uk */
      email?: string;
      /** @example 2023-09-06T22:04:58.634Z */
      joinDate?: string;
      /** @example null */
      phone?: string | null;
      /** @example 2 */
      billingAddressId?: number | null;
      /** @example 2 */
      shippingAddressId?: number | null;
      /** @example null */
      avatar?: string | null;
    };
    CustomerWithAddresses: components['schemas']['Customer'] & {
      billingAddress?: components['schemas']['Address'] & unknown;
      shippingAddress?: components['schemas']['Address'] & unknown;
    };
    Wishlist: {
      wishlist?: {
        id?: number;
        name?: string;
        username?: string;
        wishlistItems?: components['schemas']['Product'][];
      };
    };
    Cart: {
      cart?: {
        /** @example 1 */
        id?: number;
        /** @example Anthony Marks */
        name?: string;
        /** @example A-Marks9 */
        username?: string;
        cartItems?: {
          /** @example 6 */
          quantity?: number;
          product?: components['schemas']['Product'];
        }[];
      };
    };
    WishlistAltFormat: {
      customerId?: number;
      productId?: number;
    }[];
    CartAltFormat: {
      customerId?: number;
      productId?: number;
      quantity?: number;
    }[];
    Pagination: {
      /** @example 1 */
      page?: number;
      /** @example 25 */
      count?: number;
      /** @example 50 */
      totalResults?: number;
    };
    Review: {
      /** @example 1 */
      id?: number;
      /** @example 1 */
      customerId?: number;
      /** @example 12 */
      productId?: number;
      /** @example 32 */
      orderId?: number;
      /** @example Great product! Highly recommended */
      title?: string;
      /** @example Works as expected. Good value for money. Five stars! */
      body?: string;
      /** @example true */
      recommend?: boolean | null;
      /** @example 3 */
      rating?: number;
      /** @example 2022-08-23T06:38:04.750Z */
      createdAt?: string;
      customer?: {
        /** @example alexnes33 */
        username?: string;
        /** @example avatars.com/thumbnails/23 */
        avatar?: string;
      };
      product?: components['schemas']['ProductShort'];
    };
  };
  responses: {
    /** @description response returned upon successful login */
    LoginResponse: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': {
          customer?: {
            name?: string;
            username?: string;
            email?: string;
          };
        };
      };
    };
    /** @description paginated/filtered/sorted list of products */
    ProductsResponse: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Pagination'] & {
          products?: (components['schemas']['Product'] & unknown & unknown)[];
        };
      };
    };
    /** @description paginated list of a customer's recommended products */
    FavoritesResponse: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Pagination'] & {
          favorites?: ({
            addedAt?: string;
            recommend?: boolean;
            rating?: number;
            product?: components['schemas']['Product'];
          } & unknown &
            unknown)[];
        };
      };
    };
    /** @description object returned upon creating/updating a customer's account */
    CustomerResponse: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Customer'];
      };
    };
    /** @description returns all orders for a specific customer */
    OrdersResponse: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Orders'];
      };
    };
    /** @description successful creation of a new order */
    NewOrderResponse: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        /** @example {
         *       "id": 23,
         *       "customerId": 1,
         *       "billingAddressId": 1,
         *       "shippingAddressId": 1,
         *       "status": "completed",
         *       "paymentMethod": "Card",
         *       "total": 108.6,
         *       "createdAt": "2023-08-01T23:54:44.756Z",
         *       "billingAddress": {
         *         "id": 1,
         *         "addressLine1": "321 Hyatt Green",
         *         "addressLine2": "Apt. 843",
         *         "cit\"": "Grant Hill",
         *         "county": "Worcestershire",
         *         "postcode": "MZ3 1XS"
         *       },
         *       "shippingAddress": {
         *         "id": 1,
         *         "addressLine1": "321 Hyatt Green",
         *         "addressLine2": "Apt. 843",
         *         "city": "Grant Hill",
         *         "county\"": "Worcestershire",
         *         "postcode": "MZ3 1XS"
         *       },
         *       "orderItems": [
         *         {
         *           "quantity": 3,
         *           "product": {
         *             "id": 12,
         *             "name": "charging cable",
         *             "description": "premium cable made from cheap materials",
         *             "price": "36.20",
         *             "stock": 15,
         *             "categoryName": "Electronics",
         *             "supplierName": "Kryden Industries",
         *             "thumbnail": "https://loremflickr.com/647266532-12765"
         *           }
         *         }
         *       ]
         *     } */
        'application/json': components['schemas']['SingleOrder'];
      };
    };
    /** @description all of a customer's account information */
    CustomerResponseWithAddress: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['CustomerWithAddresses'];
      };
    };
    /** @description single product by id */
    SingleProductResponse: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Product'];
      };
    };
    /** @description list of reviews */
    ReviewsResponse: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Pagination'] & {
          reviews?: (components['schemas']['Review'] & unknown & unknown)[];
        };
      };
    };
    /** @description resource not found, such as for non-existent resources or invalid URL paths. */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': {
          error?: {
            /** @enum {number} */
            status?: 404;
            /** @enum {string} */
            info?: 'Not found';
          };
        };
      };
    };
    /** @description unauthorised action on a protected route, such as attempting to access or modify another customer's data */
    Unauthorised: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': {
          error?: {
            /** @enum {number} */
            status?: 403;
            /** @enum {string} */
            info?: 'Unauthorized';
          };
        };
      };
    };
    /** @description response sent for failed login attempts and attempts to access resources without valid authentication credentials. */
    Unauthenticated: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': {
          error?: {
            /** @enum {number} */
            status?: 401;
            /** @enum {string} */
            info?: 'Unauthorized' | 'Unauthenticated';
          };
        };
      };
    };
    /** @description bad request casued by incomplete or invalid request bodies. */
    SignupError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': {
          error?: {
            /** @enum {number} */
            status?: 400;
            /** @enum {string} */
            info?: 'Request body is missing required field(s).' | 'Request body fields must all be in string format.';
          };
        };
      };
    };
    /** @description bad request caused by invalid query parameters (e.g. incorrect column names leading to PSQL query errors) */
    InvalidQuery: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': {
          error?: {
            /** @enum {number} */
            status?: 400;
            info?: string;
          };
        };
      };
    };
    /** @description bad request caused by missing, invalid or constraint-violating data in request bodies. */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': {
          error?: {
            /** @enum {number} */
            status?: 400;
            /** @example Bad request */
            info?: string;
          };
        };
      };
    };
  };
  parameters: {
    /** @description Which page of results to return. The offset is calculated by multiplying the (limit) with (page minus one). */
    pageParam: number;
    /** @description How many entries (objects) to return in a listing. */
    limitParam: number;
    /** @description filter results by category */
    categoryParam: 'Consumables' | 'Replicas' | 'Exoskeletons' | 'Prototypes' | 'Cybernetics' | 'Components' | 'Upgrades' | 'Junk';
    /** @description filter results by supplier */
    supplierParam: 'Novina' | 'Mikkei Combine' | 'Sirta Foundation' | 'Ferrous Corp' | 'Volkov-Rusi' | 'G & B Supplies';
    /**
     * @description hides all products with 0 stock
     * @example true
     */
    hideOutOfStockParam: 'true' | 'false';
    /** @description order results by a specific property (column name) */
    orderByParam:
      | 'id'
      | 'name'
      | 'description'
      | 'price'
      | 'stock'
      | 'categoryName'
      | 'supplierName'
      | 'thumbnail'
      | 'avgRating'
      | 'bestsellers';
    /** @description set the sort order to ascending or descending */
    orderParam: 'asc' | 'desc';
    /**
     * @description only show products that cost at least this much.
     * @example 0.01
     */
    minPriceParam: number;
    /**
     * @description only show products that cost less than this value
     * @example 10000
     */
    maxPriceParam: number;
    /** @description returns date and id of the most recent order containing this item, or null if the customer has not previously ordered this item. */
    productIdQueryParam: number;
    /** @description allows user to choose between different JSON formats for the response object */
    formatParam: 'basic' | 'full';
    /**
     * @description The id of the customer.
     * @default 1
     */
    customerIdParam: number;
    /** @description The id of the product. */
    productIdParam: number;
    /** @description The id of the order. */
    orderIdParam: number;
    /** @description The id of the address. */
    addressIdParam: number;
    /** @description The id of the review. */
    reviewIdParam: number;
  };
  requestBodies: {
    /** @description request body requirements for updating user account */
    UpdateCustomerAccountRequest: {
      content: {
        'application/json': {
          /** @example Anthony Marks */
          name?: string;
          /** @example anthony_marks49 */
          username?: string;
          /** @example password123abc */
          password?: string;
          /** @example anthonymarks@aol.vb */
          email?: string;
          /** @example 101202422 12 */
          phone?: string | null;
          /** @example null */
          avatar?: string | null;
        };
      };
    };
    /** @description request body requirements for updating a user's address */
    UpdateCustomerAddressRequest: {
      content: {
        'application/json': components['schemas']['Address'];
      };
    };
    /** @description request body requirements for updating cart */
    UpdateCartRequest: {
      content: {
        'application/json': {
          customerId?: number;
          productId?: number;
          quantity?: number;
        }[];
      };
    };
    /** @description request body requirements for creating a new order */
    OrdersRequest: {
      content: {
        'application/json': {
          billingAddress?: components['schemas']['Address'];
          shippingAddress?: components['schemas']['Address'];
          /** @enum {string} */
          paymentMethod?: 'Card' | 'PayPal' | 'Klarna';
          item?: {
            /** @example 2 */
            productId?: number;
            /** @example 1 */
            quantity?: number;
          };
          /** @example 42.55 */
          total?: number;
        };
      };
    };
  };
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description request body requirements for login requests */
    requestBody: {
      content: {
        /** @example {
         *       "username": "alexnes",
         *       "password": "password"
         *     } */
        'application/json': unknown & components['schemas']['Login'];
      };
    };
    responses: {
      /** @description Successful login */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "customer": {
           *         "id": 1,
           *         "name": "Alex Nes",
           *         "username": "alexnes",
           *         "email": "crichton@verob.next",
           *         "joinDate": "2023-09-06T22:04:58.634Z",
           *         "phone": "+44 771-899(322)",
           *         "billingAddressId": 64,
           *         "shippingAddressId": 64,
           *         "avatar": "https://www.usatoday.com/gcdn/-mm-/5f42c4ed5a8b58c471c004003e6b867a842c9ef1/c=0-101-2800-1680/local/-/media/USATODAY/GenericImages/2014/06/22/1403454111000-FARSCAPE-BROWDER.JPG?width=660&height=373&fit=crop&format=pjpg&auto=webp",
           *         "password": "**********"
           *       }
           *     } */
          'application/json': components['responses']['LoginResponse'];
        };
      };
      401: components['responses']['Unauthenticated'];
    };
  };
  signup: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description request body requirements for signup requests */
    requestBody: {
      content: {
        'application/json': unknown & components['schemas']['Signup'];
      };
    };
    responses: {
      /** @description successful creation of a new account */
      201: components['responses']['CustomerResponse'];
      /** @description bad request caused by request bodies with missing or invalid data. */
      400: components['responses']['SignupError'];
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description successful logout */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "msg": "Successfully logged out."
           *     } */
          'application/json': {
            msg?: string;
          };
        };
      };
      401: components['responses']['Unauthenticated'];
    };
  };
  get_products: {
    parameters: {
      query?: {
        /** @description Which page of results to return. The offset is calculated by multiplying the (limit) with (page minus one). */
        page?: components['parameters']['pageParam'];
        /** @description How many entries (objects) to return in a listing. */
        limit?: components['parameters']['limitParam'];
        /** @description filter results by category */
        category?: components['parameters']['categoryParam'];
        /** @description filter results by supplier */
        supplier?: components['parameters']['supplierParam'];
        /** @description order results by a specific property (column name) */
        orderBy?: components['parameters']['orderByParam'];
        /** @description set the sort order to ascending or descending */
        order?: components['parameters']['orderParam'];
        /**
         * @description hides all products with 0 stock
         * @example true
         */
        hideOutOfStock?: components['parameters']['hideOutOfStockParam'];
        /**
         * @description only show products that cost at least this much.
         * @example 0.01
         */
        minPrice?: components['parameters']['minPriceParam'];
        /**
         * @description only show products that cost less than this value
         * @example 10000
         */
        maxPrice?: components['parameters']['maxPriceParam'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['ProductsResponse'];
    };
  };
  get_product_by_id: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The id of the product. */
        productId: components['parameters']['productIdParam'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['SingleProductResponse'];
      404: components['responses']['NotFound'];
    };
  };
  get_reviews_by_product: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The id of the product. */
        productId: components['parameters']['productIdParam'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description paginated list of products */
      200: components['responses']['ReviewsResponse'];
      /** @description Not found */
      404: components['responses']['NotFound'];
    };
  };
  get_customer_by_id: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description The id of the customer.
         * @default 1
         */
        customerId: components['parameters']['customerIdParam'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description customer's account data */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['responses']['CustomerResponseWithAddress'];
        };
      };
      403: components['responses']['Unauthorised'];
      404: components['responses']['NotFound'];
    };
  };
  update_customer: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description The id of the customer.
         * @default 1
         */
        customerId: components['parameters']['customerIdParam'];
      };
      cookie?: never;
    };
    requestBody?: components['requestBodies']['UpdateCustomerAccountRequest'];
    responses: {
      /** @description returns updated customer account details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "id": "1,",
           *       "name": "Alex Nes",
           *       "username": "alexnes",
           *       "password": "**********",
           *       "email": "alex-nes@nexus.pk",
           *       "joinDate": "2023-08-01T16:20:52.150Z",
           *       "phone": null,
           *       "billingAddressId": 1,
           *       "shippingAddressId": 1,
           *       "avatar": null
           *     } */
          'application/json': components['responses']['CustomerResponse'];
        };
      };
      400: components['responses']['BadRequest'];
      404: components['responses']['NotFound'];
    };
  };
  delete_customer: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description The id of the customer.
         * @default 1
         */
        customerId: components['parameters']['customerIdParam'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description successful account deletion */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "msg": "User Andrddeane36 has been deleted.",
           *       "deletedUser": {
           *         "id": 6,
           *         "name": "Andre Ane",
           *         "username": "Andranna8",
           *         "email": "andrea8@yayaya.com"
           *       }
           *     } */
          'application/json': {
            msg?: string;
            deletedUser?: {
              id?: number;
              name?: string;
              username?: string;
              email?: string;
            };
          };
        };
      };
      404: components['responses']['NotFound'];
    };
  };
  get_cart_items: {
    parameters: {
      query?: {
        /** @description allows user to choose between different JSON formats for the response object */
        format?: components['parameters']['formatParam'];
      };
      header?: never;
      path: {
        /**
         * @description The id of the customer.
         * @default 1
         */
        customerId: components['parameters']['customerIdParam'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description get customer's cart items */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "cart": {
           *         "id": 1,
           *         "name": "Alex Nes",
           *         "username": "alexnes",
           *         "cartItems": [
           *           {
           *             "quantity": 2,
           *             "product": {
           *               "id": 56,
           *               "name": "skateboard",
           *               "description": "XL adult skateboard with a single wheel",
           *               "price": "416.72",
           *               "stock": 12,
           *               "categoryName": "Sports",
           *               "supplierName": "John's Sporting Goods",
           *               "thumbnail": "https://loremflickr.com/640/480/Garden?lock=1158606886010880"
           *             }
           *           },
           *           {
           *             "quantity": 1,
           *             "product": {
           *               "id": 56,
           *               "name": "bicarbonate of soda",
           *               "description": "part of the baking collection",
           *               "price": "2.24",
           *               "stock": 13,
           *               "categoryName": "Food",
           *               "supplierName": "Uncle Baltar's Treats",
           *               "thumbnail": "https://avatars.com/commerce/food/7225"
           *             }
           *           }
           *         ]
           *       }
           *     } */
          'application/json': components['schemas']['Cart'] | components['schemas']['CartAltFormat'];
        };
      };
      404: components['responses']['NotFound'];
    };
  };
  udpate_cart: {
    parameters: {
      query?: {
        /** @description allows user to choose between different JSON formats for the response object */
        format?: components['parameters']['formatParam'];
      };
      header?: never;
      path: {
        /**
         * @description The id of the customer.
         * @default 1
         */
        customerId: components['parameters']['customerIdParam'];
      };
      cookie?: never;
    };
    requestBody: components['requestBodies']['UpdateCartRequest'];
    responses: {
      /** @description returns updated cart */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Cart'] | components['schemas']['CartAltFormat'];
        };
      };
      400: components['responses']['BadRequest'];
      403: components['responses']['Unauthorised'];
    };
  };
  get_wishlist_items: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The id of the customer. */
        customerId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description a customer's wishlist items */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /** @example {
           *       "wishlist": {
           *         "id": 1,
           *         "name": "Alex Nes",
           *         "username": "alexnes",
           *         "wishlistItems": [
           *           {
           *             "product": {
           *               "id": 12,
           *               "name": "sunglasses",
           *               "description": "polarized brown lenses",
           *               "price": "136.82",
           *               "stock": 184,
           *               "categoryName": "Accessories",
           *               "supplierName": "Kris & Sons",
           *               "thumbnail": "https://loremflickr.com/640/480/Garden?lock=1158606886010880"
           *             }
           *           },
           *           {
           *             "product": {
           *               "id": 56,
           *               "name": "brown leather shoes",
           *               "description": "fake leather brown shoes with tassels",
           *               "price": "36.24",
           *               "stock": 13,
           *               "categoryName": "Shoes",
           *               "supplierName": "Jefferson Ltd",
           *               "thumbnail": "https://avatars.com/commerce/shoes/23443"
           *             }
           *           }
           *         ]
           *       }
           *     } */
          'application/json': components['schemas']['Wishlist'] | components['schemas']['WishlistAltFormat'];
        };
      };
      403: components['responses']['Unauthorised'];
      404: components['responses']['NotFound'];
    };
  };
  update_wishlist: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The id of the customer. */
        customerId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description returns updated wishlist */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Cart'] | components['schemas']['CartAltFormat'];
        };
      };
      400: components['responses']['BadRequest'];
    };
  };
  get_orders: {
    parameters: {
      query?: {
        /** @description returns date and id of the most recent order containing this item, or null if the customer has not previously ordered this item. */
        productId?: components['parameters']['productIdQueryParam'];
      };
      header?: never;
      path: {
        /**
         * @description The id of the customer.
         * @default 1
         */
        customerId: components['parameters']['customerIdParam'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['OrdersResponse'];
      400: components['responses']['BadRequest'];
      404: components['responses']['NotFound'];
    };
  };
  create_order: {
    parameters: {
      query?: {
        /** @description returns date and id of the most recent order containing this item, or null if the customer has not previously ordered this item. */
        productId?: components['parameters']['productIdQueryParam'];
      };
      header?: never;
      path: {
        /**
         * @description The id of the customer.
         * @default 1
         */
        customerId: components['parameters']['customerIdParam'];
      };
      cookie?: never;
    };
    requestBody: components['requestBodies']['OrdersRequest'];
    responses: {
      201: components['responses']['NewOrderResponse'];
      400: components['responses']['BadRequest'];
      404: components['responses']['NotFound'];
    };
  };
  get_favorites: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The id of the customer. */
        customerId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Returns list of products that have been marked as 'recommended' by the customer. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['responses']['FavoritesResponse'];
        };
      };
      404: components['responses']['NotFound'];
    };
  };
  get_order_by_id: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description The id of the customer.
         * @default 1
         */
        customerId: components['parameters']['customerIdParam'];
        /** @description The id of the order. */
        orderId: components['parameters']['orderIdParam'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description get all the information about a specific order */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SingleOrder'];
        };
      };
      404: components['responses']['NotFound'];
    };
  };
  get_reviews_by_customer: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description The id of the customer.
         * @default 1
         */
        customerId: components['parameters']['customerIdParam'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['ReviewsResponse'];
      404: components['responses']['NotFound'];
    };
  };
  create_address: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description The id of the customer.
         * @default 1
         */
        customerId: components['parameters']['customerIdParam'];
      };
      cookie?: never;
    };
    requestBody: components['requestBodies']['UpdateCustomerAddressRequest'];
    responses: {
      /** @description Allows customer to create or edit an address on their account. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['responses']['CustomerResponseWithAddress'];
        };
      };
      400: components['responses']['BadRequest'];
    };
  };
  delete_address: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description The id of the customer.
         * @default 1
         */
        customerId: components['parameters']['customerIdParam'];
        /** @description The id of the address. */
        addressId: components['parameters']['addressIdParam'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description address successfully deleted from customer's account, leaving behind a null value */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['responses']['CustomerResponseWithAddress'];
        };
      };
      404: components['responses']['NotFound'];
    };
  };
  get_categories: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Returns list of all categories. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            categories?: {
              id?: number;
              name?: string;
              description?: string;
              thumbnail?: string;
              /** @description the total number of unique products that fall under this category */
              products?: string;
            }[];
          };
        };
      };
    };
  };
  get_suppliers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Returns list of all suppliers. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            suppliers?: {
              id?: number;
              name?: string;
              location?: string;
              establishYear?: number;
              thumbnail?: string;
              /** @description the total number of unique products that are sold by this supplier */
              products?: string;
            }[];
          };
        };
      };
    };
  };
  get_reviews: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Returns the first 25 reviews, sorted by most recent first. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['responses']['ReviewsResponse'];
        };
      };
    };
  };
  update_review: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description fields required for updating a review */
    requestBody?: {
      content: {
        'application/json': unknown & components['schemas']['Review'];
      };
    };
    responses: {
      /** @description Returns the newly created review. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            newReview?: components['schemas']['Review'];
          };
        };
      };
      400: components['responses']['BadRequest'];
    };
  };
  get_review_by_id: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The id of the review. */
        reviewId: components['parameters']['reviewIdParam'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description returns all relevant data for a single review. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Review'];
        };
      };
      404: components['responses']['NotFound'];
    };
  };
  delete_review: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The id of the review. */
        reviewId: components['parameters']['reviewIdParam'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description returns the deleted review. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Review'];
        };
      };
      404: components['responses']['NotFound'];
    };
  };
}
