name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - dev
      - acc
      - main

jobs:

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Create environment.ts for DEV
        run: |
          mkdir -p src/environments
          echo "export const environment = {
            production: false,
            apiUrl: 'https://dev.api.educrm.uz',
            firebaseConfig: {
              apiKey: '${{ secrets.FIREBASE_API_KEY }}',
              authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}',
              projectId: '${{ secrets.FIREBASE_PROJECT_ID }}',
              storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}',
              messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}',
              appId: '${{ secrets.FIREBASE_APP_ID }}',
              measurementId: '${{ secrets.FIREBASE_MEASUREMENT_ID }}'
            }
          };" > src/environments/environment.ts

      - name: Build Angular project (DEV)
        run: npm run build:dev

      - name: Deploy to Firebase (DEV)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEV }}'
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          projectId: 'educrm-dev'
          channelId: 'dev'


  deploy-acc:
    if: github.ref == 'refs/heads/acc'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Create environment.ts for ACC
        run: |
          mkdir -p src/environments
          echo "export const environment = {
            production: false,
            apiUrl: 'https://acc.api.educrm.uz',
            firebaseConfig: {
              apiKey: '${{ secrets.FIREBASE_API_KEY }}',
              authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}',
              projectId: '${{ secrets.FIREBASE_PROJECT_ID }}',
              storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}',
              messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}',
              appId: '${{ secrets.FIREBASE_APP_ID }}',
              measurementId: '${{ secrets.FIREBASE_MEASUREMENT_ID }}'
            }
          };" > src/environments/environment.ts

      - name: Build Angular project (ACC)
        run: npm run build:acc

      - name: Deploy to Firebase (ACC)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ACC }}'
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          projectId: 'educrm-acc'
          channelId: 'acc'


  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Create environment.ts for PROD
        run: |
          mkdir -p src/environments
          echo "export const environment = {
            production: true,
            apiUrl: 'https://api.educrm.uz',
            firebaseConfig: {
              apiKey: '${{ secrets.FIREBASE_API_KEY }}',
              authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}',
              projectId: '${{ secrets.FIREBASE_PROJECT_ID }}',
              storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}',
              messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}',
              appId: '${{ secrets.FIREBASE_APP_ID }}',
              measurementId: '${{ secrets.FIREBASE_MEASUREMENT_ID }}'
            }
          };" > src/environments/environment.ts

      - name: Build Angular project (PROD)
        run: npm run build:prod

      - name: Deploy to Firebase (PROD)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROD }}'
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          projectId: 'educrm-prod'
          channelId: 'live'
